---
version: "3.7"

services:
  api:
    container_name: dm-api
    build:
      context: .
    stdin_open: true
    tty: true
    restart: unless-stopped
    volumes:
      - ./src:/var/www
    ports:
      - "5000:5000"
      - "8001:8000"
    env_file:
      - .env
    networks:
      - backend
volumes:
  mongodb_data:


networks:
  backend:
