version: "3"

services:
  api:
    container_name: dm-api
    build:
      context: .
    stdin_open: true
    tty: true
    restart: unless-stopped
    volumes:
      - ./src:/var/www
    ports:
      - "5000:5000"
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - backend
  db:
    image: mongo:latest
    container_name: dm-mongo
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27016:27017"
    env_file:
      - .env
    networks:
      - backend
  browserless:
    image: browserless/chrome:latest
    container_name: dm-browserless
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - backend

volumes:
  mongodb_data:

networks:
  backend:
