"""__init__."""
# Standard Python Libraries
from typing import Dict, List

PROXIES: List[Dict] = [
    {
        "name": "Trusted Source",
        "url": "https://trustedsource.org/",
        "categorize_url": "https://trustedsource.org/",
        "check_url": "https://trustedsource.org/",
    },
    {
        "name": "Blue Coat",
        "url": "https://sitereview.bluecoat.com/#/",
        "categorize_url": "https://sitereview.bluecoat.com/#/",
        "check_url": "https://sitereview.bluecoat.com/#/",
    },
    {
        "name": "Fortiguard",
        "url": "https://www.fortiguard.com/faq/wfratingsubmit",
        "categorize_url": "https://www.fortiguard.com/faq/wfratingsubmit",
        "check_url": "https://www.fortiguard.com/webfilter",
    },
    {
        "name": "Palo Alto Networks",
        "url": "https://urlfiltering.paloaltonetworks.com/",
        "categorize_url": "https://urlfiltering.paloaltonetworks.com/",
        "check_url": "https://urlfiltering.paloaltonetworks.com/",
    },
    {
        "name": "Trend Micro",
        "url": "https://global.sitesafety.trendmicro.com/",
        "categorize_url": "https://global.sitesafety.trendmicro.com/",
        "check_url": "https://global.sitesafety.trendmicro.com/",
    },
    # {
    #     "name": "Websense",
    #     "url": "http://csi.websense.com",
    #     "categorize_url": "http://csi.websense.com",
    #     "check_url": "http://csi.websense.com",
    # },
    {
        "name": "Cisco Talos",
        "url": "https://talosintelligence.com/reputation_center",
        "categorize_url": "https://talosintelligence.com/reputation_center",
        "check_url": "https://talosintelligence.com/reputation_center",
    },
    {
        "name": "IBM X Force",
        "url": "https://exchange.xforce.ibmcloud.com/",
        "categorize_url": "https://exchange.xforce.ibmcloud.com/",
        "check_url": "https://exchange.xforce.ibmcloud.com/",
    },
]

CATEGORIES = {
    "Activist Groups": {
        "Blue Coat": "Activist Groups",
        "Trusted Source": "Politics/Opinion",
        "Fortiguard": "Political Organizations",
        "Palo Alto Networks": "Philosophy and Political Advocacy",
        "Trend Micro": "Politics",
    },
    "Advertising": {
        "Blue Coat": "Activist Groups",
        "Trusted Source": "Web Ads/Analytics",
        "Fortiguard": "Advertising",
        "Palo Alto Networks": "Web Advertisements",
        "Trend Micro": "Web Advertisements",
    },
    "Advocacy Organizations": {
        "Blue Coat": "Political/Social Advocacy",
        "Trusted Source": "Politics/Opinion",
        "Fortiguard": "Advocacy Organizations",
        "Palo Alto Networks": "Philosophy and Political Advocacy",
        "Trend Micro": "Politics",
    },
    "Alternative Beliefs": {
        "Trusted Source": "Religion/Ideology",
        "Blue Coat": "Alternative Spirituality/Belief",
        "Fortiguard": "Alternative Beliefs",
        "Palo Alto Networks": "Philosophy and Political Advocacy",
        "Trend Micro": "Alternative Journals",
    },
    "Art": {
        "Trusted Source": "Art/Culture/Heritage",
        "Blue Coat": "Art/Culture",
        "Fortiguard": "Arts and Culture",
        "Palo Alto Networks": "Entertainment and Arts",
        "Trend Micro": "Arts",
    },
    "Auction": {
        "Trusted Source": "Auctions/Classifieds",
        "Blue Coat": "Auctions",
        "Fortiguard": "Auction",
        "Palo Alto Networks": "Auctions",
        "Trend Micro": "Auctions",
    },
    "Blogs": {
        "Trusted Source": "Blogs/Wiki",
        "Blue Coat": "Social Networking",
        "Fortiguard": "Social Networking",
        "Palo Alto Networks": "Social Networking",
        "Trend Micro": "Blogs / Web Communications",
    },
    "Financial Brokerage": {
        "Trusted Source": "Finance/Banking",
        "Blue Coat": "Brokerage/Trading",
        "Fortiguard": "Brokerage and Trading",
        "Palo Alto Networks": "Business and Economy",
        "Trend Micro": "Brokerages / Trading",
    },
    "Business": {
        "Trusted Source": "Business",
        "Blue Coat": "Business/Economy",
        "Fortiguard": "Business",
        "Palo Alto Networks": "Business and Economy",
        "Trend Micro": "Business / Economy",
    },
    "Charitable Organizations": {
        "Trusted Source": "Business",
        "Blue Coat": "Charitable/Non-Profit",
        "Fortiguard": "Charitable Organizations",
        "Palo Alto Networks": "Business and Economy",
        "Trend Micro": "Business / Economy",
    },
    "Chat": {
        "Trusted Source": "Chat",
        "Blue Coat": "Chat (IM)/SMS",
        "Fortiguard": "Instant Messaging",
        "Palo Alto Networks": "Internet Communications and Telephony",
        "Trend Micro": "Chat / Instant Messaging",
    },
    "Computers / Internet": {
        "Trusted Source": "Internet Services",
        "Blue Coat": "Computer/Information Security",
        "Fortiguard": "Information Technology",
        "Palo Alto Networks": "Computer and Internet Info",
        "Trend Micro": "Computers / Internet",
    },
    "Content Delivery Networks": {
        "Trusted Source": "Content Server",
        "Blue Coat": "Content Delivery Networks",
        "Fortiguard": "Content Servers",
        "Palo Alto Networks": "Content Delivery Networks",
        "Trend Micro": "Pay to Surf",
    },
    "Dating": {
        "Trusted Source": "Dating/Personals",
        "Blue Coat": "Personals/Dating",
        "Fortiguard": "Dating",
        "Palo Alto Networks": "Dating",
        "Trend Micro": "Personals / Dating",
    },
    "Education": {
        "Trusted Source": "Education/Reference",
        "Blue Coat": "Education",
        "Fortiguard": "Education",
        "Palo Alto Networks": "Educational Institutions",
        "Trend Micro": "Education",
    },
    "Entertainment": {
        "Trusted Source": "Entertainment",
        "Blue Coat": "Entertainment",
        "Fortiguard": "Entertainment",
        "Palo Alto Networks": "Entertainment and Arts",
        "Trend Micro": "Entertainment",
    },
    "Finance": {
        "Trusted Source": "Finance/Banking",
        "Blue Coat": "Finance",
        "Fortiguard": "Finance and Banking",
        "Palo Alto Networks": "Financial Services",
        "Trend Micro": "Financial Services",
    },
    "For Kids": {
        "Trusted Source": "For Kids",
        "Blue Coat": "For Kids",
        "Fortiguard": "Child Education",
        "Palo Alto Networks": "Entertainment and Arts",
        "Trend Micro": "For Kids",
    },
    "Games": {
        "Trusted Source": "Games",
        "Blue Coat": "Games",
        "Fortiguard": "Games",
        "Palo Alto Networks": "Games",
        "Trend Micro": "Games",
    },
    "News": {
        "Trusted Source": "General News",
        "Blue Coat": "News",
        "Fortiguard": "News and Media",
        "Palo Alto Networks": "News",
        "Trend Micro": "News / Media",
    },
    "Government": {
        "Trusted Source": "Government/Military",
        "Blue Coat": "Government/Legal",
        "Fortiguard": "Government and Legal Organizations",
        "Palo Alto Networks": "Government",
        "Trend Micro": "Government / Legal",
    },
    "Health": {
        "Trusted Source": "Health",
        "Blue Coat": "Health",
        "Fortiguard": "Health and Wellness",
        "Palo Alto Networks": "Health and Medicine",
        "Trend Micro": "Health",
    },
    "Humor": {
        "Trusted Source": "Humor/Comics",
        "Blue Coat": "Humor/Jokes",
        "Fortiguard": "Entertainment",
        "Palo Alto Networks": "Entertainment and Arts",
        "Trend Micro": "Humor",
    },
    "Hunting and Fishing": {
        "Trusted Source": "Entertainment",
        "Blue Coat": "Entertainment",
        "Fortiguard": "Entertainment",
        "Palo Alto Networks": "Hunting and Fishing",
        "Trend Micro": "Gun Clubs / Hunting",
    },
    "Job Search": {
        "Trusted Source": "Job Search",
        "Blue Coat": "Job Search/Careers",
        "Fortiguard": "Job Search",
        "Palo Alto Networks": "Job Search",
        "Trend Micro": "Job Search / Careers",
    },
    "Military": {
        "Trusted Source": "Government/Military",
        "Blue Coat": "Military",
        "Fortiguard": "Armed Forces",
        "Palo Alto Networks": "Military",
        "Trend Micro": "Military",
    },
    "Politics/Opinion": {
        "Trusted Source": "Politics/Opinion",
        "Blue Coat": "Political/Social Advocacy",
        "Fortiguard": "Political Organizations",
        "Palo Alto Networks": "Philosophy and Political Advocacy",
        "Trend Micro": "Politics",
    },
    "Real Estate": {
        "Trusted Source": "Real Estate",
        "Blue Coat": "Real Estate",
        "Fortiguard": "Real Estate",
        "Palo Alto Networks": "Real Estate",
        "Trend Micro": "Real Estate",
    },
    "Religion": {
        "Trusted Source": "Religion/Ideology",
        "Blue Coat": "Religion",
        "Fortiguard": "Global Religion",
        "Palo Alto Networks": "Religion",
        "Trend Micro": "Religion",
    },
    "Restaurants": {
        "Trusted Source": "Restaurants",
        "Blue Coat": "Restaurants/Food",
        "Fortiguard": "Restaurant and Dining",
        "Palo Alto Networks": "Shopping",
        "Trend Micro": "Restaurants / Food",
    },
    "Search Engines": {
        "Trusted Source": "Search Engines",
        "Blue Coat": "Search Engines/Portals",
        "Fortiguard": "Search Engines and Portals",
        "Palo Alto Networks": "Search Engines",
        "Trend Micro": "Search Engines / Portals",
    },
    "Shopping": {
        "Trusted Source": "Online Shopping",
        "Blue Coat": "Shopping",
        "Fortiguard": "Shopping",
        "Palo Alto Networks": "Shopping",
        "Trend Micro": "Shopping",
    },
    "Social Networking": {
        "Trusted Source": "Social Networking",
        "Blue Coat": "Social Networking",
        "Fortiguard": "Social Networking",
        "Palo Alto Networks": "Social Networking",
        "Trend Micro": "Social Networking",
    },
    "Sports": {
        "Trusted Source": "Sports",
        "Blue Coat": "Sports/Recreation",
        "Fortiguard": "Sports",
        "Palo Alto Networks": "Sports",
        "Trend Micro": "Sports",
    },
    "Travel": {
        "Trusted Source": "Travel",
        "Blue Coat": "Travel",
        "Fortiguard": "Travel",
        "Palo Alto Networks": "Travel",
        "Trend Micro": "Travel",
    },
    "Web Hosting": {
        "Trusted Source": "Internet Services",
        "Blue Coat": "Web Hosting",
        "Fortiguard": "Web Hosting",
        "Palo Alto Networks": "Web Hosting",
        "Trend Micro": "Web Hosting",
    },
}
