name: Pull Request

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
      - name: Set up pre-commit hook environments
        run: pre-commit install-hooks
      - name: pre-commit autoupdate
        run: pre-commit autoupdate
      - name: Run pre-commit on all files
        run: pre-commit run --all-files

  python_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: create env file
        run: cp ./etc/env.dist .env
      - name: Install Test Requirements
        run: pip install -r requirements-test.txt
      - name: Install Requirements
        run: pip install -r requirements.txt --no-deps
      - name: Pytest/Coverage
        run: pytest ./src/tests/ --disable-warnings
